<?php

/**
 * InseeDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InseeDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return InseeDataTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InseeData');
    }
}