<?php

/**
 * PostalCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostalCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PostalCodeTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostalCode');
    }
}