<?php

/**
 * SecuriteDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SecuriteDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return SecuriteDataTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SecuriteData');
    }
}